### ISSUE TITLE
SCOOPED! 🙀 

### ISSUE THREAD

**Issue by dojoe** [gregdavill/PD-sniffer#6]
Wow, what are the odds?

Turns out I have the exact same project going for a while now and am just preparing for release on GitHub too :)

I made a Twinkie clone with the exact same design goal - to be made by hand by mere mortals. My design is called the Twonkie (because it's a somewhat wonky Twinkie), I think I got all the kinks out after three board revisions now, and I have also gotten the firmware build up and running and managed to extract it from the humongous Chromium build system so it's much easier to build.

So to make sure we don't duplicate each other's work more than necessary, if you just wait for a bit (shouldn't be long) I'll have a nice and easy FW build for you :)

**Comment by whitequark** [comment]
Superb work re firmware!

**Comment by dojoe** [comment]
Alright, here's mine now: https://github.com/dop3j0e/Twonkie  FW sources will come very soon!
I added a link back to your project in my readme too.

**Comment by dojoe** [comment]
I uploaded FW sources to my Twonkie repo and will close this issue now.
